language: go

go:
  - 1.8
  - 1.9

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install: go get -v -u github.com/Masterminds/glide && glide install

notifications:
  email: false

script: go test 
